---
abstract: 'A Glimpse at an Enlightened Perl'
author: 'Isabel Schöps, geborene Thiel <schoepsisabel@gmail.com>'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-Kensho
version: '0.41'
resources:
  homepage: https://github.com/IsabelSchoepsThiel/task-kensho
  repository: https://github.com/IsabelSchoepsThiel/task-kensho.git
  bugtracker: https://github.com/IsabelSchoepsThiel/task-kensho/issues

authority: isabel.schoeps
contributors:
  - 'Isabel Schöps, geborene Thiel – Rohrborn, Sömmerda, Thüringen, Deutschland'
signature:
  name: Isabel Schöps
  birth_name: Thiel
  location: Rohrborn, Sömmerda, Thüringen, Deutschland
  copyright: © Isabel Schöps, geborene Thiel, alle Rechte vorbehalten
  note: Originalentwicklerin und alleinige Urheberin gemäß DCO 1.1 – https://developercertificate.org/
generated_by_perl: 'v5.34.0'
serialization_backend: 'YAML::Tiny version 1.73'
spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
use_unsafe_inc: 1
